### ISSUE TITLE
contributors images in readme file

### ISSUE THREAD

**Issue by Beast71421** [MrKrishnaAgarwal/MrKrishnaAgarwal#16]
![image](https://user-images.githubusercontent.com/78417225/194754193-108799d0-5e7c-4536-a278-d5d993179ec6.png)

like this

**Comment by Beast71421** [comment]
can i have this issue @MrKrishnaAgarwal

**Comment by MrKrishnaAgarwal** [comment]
Hey @Beast71421,
Its not required here, becuase it's my personal profile Readme.

Only I am contributor of it so no need.

Please open issues with relevant fix.

**Comment by Beast71421** [comment]
ok i will try it with other repo

**Comment by MrKrishnaAgarwal** [comment]
> ok i will try it with other repo
> 

Sure 👍🏻
